### ISSUE TITLE
App crashes after when i updated

### ISSUE THREAD

**Issue by Furygo33** [KotatsuApp/Kotatsu#1078]
### Brief summary

I updated the app and it crashed when I tried to access it.

### Steps to reproduce

I can't add a screenshot, the phone is bad. As for the problem, I updated the app, it was working fine before the update, but after updating, when I enter the app, I get the error "sorry, the app has stopped"

### Kotatsu version

7.5.0

### Android version

6.0.1

### Device

Samsung s4 mini(rom:aicp)

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Blehbleher** [comment]
I have the same issue,a way to maybe go around it was close internet,open then open the internet but it's only temporary as it will crash again soon,also when downloading it will give an error as "channel was closed

**Comment by Blehbleher** [comment]
> I have the same issue,a way to maybe go around it was close internet,open then open the internet but it's only temporary as it will crash again soon,also when downloading it will give an error as "channel was closed

To add on, u can't access downloaded mangas they say "network error" even tho they are downloaded, a workaround would be opening them in incognito

**Comment by Furygo33** [comment]
> I have the same issue,a way to maybe go around it was close internet,open then open the internet but it's only temporary as it will crash again soon,also when downloading it will give an error as "channel was closed

Exactly, I did what you said, but the app crashed for me right after, so I went back to the previous version.

**Comment by Koitharu** [comment]
Can someone share the crash log? I cannot reproduce the crash there are no reports in our ACRA

**Comment by Blehbleher** [comment]
> Can someone share the crash log? I cannot reproduce the crash there are no reports in our ACRA

am sorry but how do we do this on mobile app?
it basically just gives "kotatsu stopped working" after opening kotatsu while internet is on

Uploading VID-20240904-WA0000.mp4…

**Comment by Blehbleher** [comment]
https://github.com/user-attachments/assets/d4576c22-ff1d-44af-b668-c9b7d13c2050

Here is how it looks like

**Comment by plokm21** [comment]
I'm also having the same issue although the temporary "turn off wifi before opening the app and turning it back on again trick" fixes the issue somewhat i can browse and read manga just fine after it.
the crashes might be related to the act of downloading and reading downloaded manga since those seem to be the most consistent causes of crashes after turning the wifi back on everything else seems to work fine.

**Comment by Ero-gamer** [comment]
I have the same issue, it seem this bug is introduced in v7.5. I never had this issue before using Kotatsu previous versions for months. Also app crash after 5 sec when chapters auto updates + suggestions updates notification show up, I had to downgrade to v7.4.3 to disable auto updates to use v7.5 only to get another offline reading bug.

![Screenshot_2024-09-05-00-04-15-23](https://github.com/user-attachments/assets/9d616c6c-63c9-45f8-8a30-fbd47dd84f19)

**Comment by KingSaul22** [comment]
This happens to me too. 
The log includes from the moment I opened the app until it crashed.
Tell me if you want another log trying with airplane mode.

[log_2024_09_05_12_32_07.log](https://github.com/user-attachments/files/16892937/log_2024_09_05_12_32_07.log)

**Comment by Ero-gamer** [comment]
> 



> You can use [LogcatReader](https://github.com/darshanparajuli/LogcatReader) or similar apps to read the logcat from an Android device directly. It would be really useful since we cannot reproduce this crash

v7.5.1 seem stable and works as intended. Thanks for the fast hotfix.

**Comment by Furygo33** [comment]
> > 
> 
> > [LogcatReader](https://github.com/darshanparajuli/LogcatReader) veya benzeri uygulamaları kullanarak logcat'i doğrudan bir Android cihazdan okuyabilirsiniz. Bu çökmeyi yeniden üretemeyeceğimizden bu gerçekten faydalı olacaktır.
> 
> v7.5.1 kararlı görünüyor ve amaçlandığı gibi çalışıyor. Hızlı düzeltme için teşekkürler.

but the error still going

**Comment by Koitharu** [comment]
@KingSaul22  Thank you so much for the logs

Could you please check this build?
[app-release.apk.zip](https://github.com/user-attachments/files/16897338/app-release.apk.zip)
(this is not a zip, just remove the ".zip" suffix from filename)

**Comment by Furygo33** [comment]
> @KingSaul22 Günlükler için çok teşekkür ederim
> 
> Lütfen bu yapıyı kontrol edebilir misiniz? [app-release.apk.zip](https://github.com/user-attachments/files/16897338/app-release.apk.zip) (bu bir zip dosyası değil, sadece dosya adından ".zip" ekini kaldırın)
Thank you very much, the problem is solved, thanks for your help and I have one more question."Value return this of type java.lang.String cannot be converted to JSONObject " What is problem? Could it be because the website requires verification to read?

**Comment by Koitharu** [comment]
@Furygo33 needs more info. Sounds like a parser issue but more details required

**Comment by KingSaul22** [comment]
> @KingSaul22  Thank you so much for the logs
> 
> Could you please check this build?
> [app-release.apk.zip](https://github.com/user-attachments/files/16897338/app-release.apk.zip)
> (this is not a zip, just remove the ".zip" suffix from filename)
> 

Looks like the problem was solved.
Thanks, all good for the moment

**Comment by plokm21** [comment]
> @KingSaul22 Thank you so much for the logs
> 
> Could you please check this build? [app-release.apk.zip](https://github.com/user-attachments/files/16897338/app-release.apk.zip) (this is not a zip, just remove the ".zip" suffix from filename)

Yeah i can also vouch for this it fixed my issues too.
i tried updating to the official 7.5.1 relase but it didn't fix it this release did thank you.

**Comment by ztimms73** [comment]
Fixed in 7.5.2
